# Generated by Django 5.2.7 on 2026-08-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tbl_nomenclatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['perf_usuario__username'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_perf',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
