# Generated by Django 5.2.7 on 2026-08-13 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_options_alter_profile_id_perf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='perf_desactivado_fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='profile',
            name='perf_desactivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_desactivados', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
    ]
