# Generated by Django 5.2.7 on 2026-08-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imagen',
            field=models.FileField(blank=True, help_text='Imagen representativa de la categoría (JPG/PNG/WEBP).', null=True, upload_to='categorias/', verbose_name='Imagen'),
        ),
    ]
