# Generated by Django 5.2.7 on 2026-08-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tbl_nomenclatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['cate_orden', 'cate_nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['prod_categoria__cate_orden', 'prod_nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='tbl_product_prod_ac_8fa720_idx',
            old_name='products_pr_activ_1234ab_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='id_cate',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_prod',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
