# Generated by Django 5.2.7 on 2026-08-13 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cate_desactivado_fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivada el'),
        ),
        migrations.AddField(
            model_name='category',
            name='cate_desactivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_desactivadas', to=settings.AUTH_USER_MODEL, verbose_name='Desactivada por'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_desactivado_fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desactivado el'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_desactivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_desactivados', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
    ]
