# Generated by Django 5.2.7 on 2026-08-14 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('producto', 'Producto'), ('categoria', 'Categoría'), ('empleado', 'Empleado')], max_length=20, verbose_name='Tipo')),
                ('accion', models.CharField(choices=[('desactivo', 'Desactivó'), ('reactivo', 'Reactivó')], max_length=20, verbose_name='Acción')),
                ('entidad_nombre', models.CharField(max_length=200, verbose_name='Entidad')),
                ('entidad_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de la entidad')),
                ('texto', models.TextField(verbose_name='Mensaje')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('editado', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Emisor')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='MensajeEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('leido_en', models.DateTimeField(blank=True, null=True, verbose_name='Leído el')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='mensajes.mensaje', verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Entrega de mensaje',
                'verbose_name_plural': 'Entregas de mensaje',
                'unique_together': {('mensaje', 'destinatario')},
            },
        ),
    ]
