# Generated by Django 5.2.7 on 2026-08-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='visto_por_admin',
            field=models.BooleanField(default=False, help_text='Estado global: 1 visto (emisor) hasta que algún admin abra el mensaje; recién ahí pasa a 2 vistos.', verbose_name='Visto por el admin'),
        ),
    ]
