# Generated by Django 6.1 on 2026-08-07 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_clave_acceso_order_direccion_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
    ]
