# Generated by Django 6.1 on 2026-08-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='facturar',
            field=models.BooleanField(default=False, help_text='Al completar el pedido se emite factura electrónica.', verbose_name='Cliente pide factura'),
        ),
    ]
