# Generated by Django 6.1 on 2026-08-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_facturar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='facturar',
        ),
    ]
