# Generated by Django 6.1 on 2026-08-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_facturar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('04', 'RUC'), ('05', 'Cédula'), ('06', 'Pasaporte'), ('07', 'Consumidor Final')], max_length=2, verbose_name='Tipo de identificación')),
                ('identificacion', models.CharField(max_length=20, verbose_name='Identificación')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre / Razón social')),
                ('direccion', models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('tipo_identificacion', 'identificacion'), name='uniq_cliente_tipo_identificacion')],
            },
        ),
    ]
