# Generated by Django 6.1 on 2026-08-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='order',
            name='apellidos',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='order',
            name='nombres',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Nombres'),
        ),
    ]
