# Generated by Django 5.2.7 on 2026-08-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_cliente_apellidos_cliente_nombres_order_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='clave_acceso',
        ),
        migrations.RemoveField(
            model_name='order',
            name='secuencial_factura',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal_cero',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal_iva',
        ),
        migrations.RemoveField(
            model_name='order',
            name='valor_iva',
        ),
    ]
