# Generated by Django 5.2.7 on 2026-08-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_tbl_nomenclatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['clie_nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-pedi_creado'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='tbl_pedidos_pedi_ac_0e807e_idx',
            old_name='orders_orde_pedi_ac_5678cd_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='tbl_pedidos_pedi_ve_5ba6ce_idx',
            old_name='orders_orde_pedi_ve_9012ef_idx',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_clie',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_pedi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id_deta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
